pipeline:
  docker:
    image: plugins/docker
    username: ktruckenmiller
    password: ${password}
    repo: ktruckenmiller/fetchit-downloads
    tags:
      - latest

  notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    username: drone
    when:
      status: [ success, failure ]
